name: release-please
on:
  push:
    branches:
      - main
      - release-**
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: release-please-action
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: ${{ github.ref_name }}
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'
  create-release-branch:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v2
      - name: create release-branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b release-${{ needs.release-please.outputs.tag_name }}
          git push origin release-${{ needs.release-please.outputs.tag_name }}
  delete-release-branch:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created && github.ref_name != 'main' }}
    steps:
      - uses: actions/checkout@v2
      - name: delete release-branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branch: ${{ github.ref_name }}
